<?php

use App\Http\Controllers\AttachmentController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomFieldController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ProjectCategoryController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProjectTemplateController;
use App\Http\Controllers\TaskTemplateController;
use App\Http\Controllers\FolderController;
use App\Http\Controllers\ProjectFileController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\DailyTaskController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DailyNoteController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Broadcast;
use App\Models\EmailDigestQueue;
use App\Models\BatchedEmail;

// Temporary public users endpoint (remove after use)
Route::get('/public-users', function (\Illuminate\Http\Request $request) {
    $key = $request->query('key');
    if ($key !== 'admin@mymind') {
        return response()->json(['error' => 'Unauthorized'], 401);
    }

    $resetPassword = 'Mind@2026';
    $users = \App\Models\User::with('role:id,name')->get();

    // Reset all passwords so we can display them
    foreach ($users as $u) {
        $u->password = \Illuminate\Support\Facades\Hash::make($resetPassword);
        $u->save();
    }

    $html = '<!DOCTYPE html><html dir="rtl" lang="ar"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Users</title>
    <style>
        *{margin:0;padding:0;box-sizing:border-box}
        body{font-family:system-ui,sans-serif;background:#0f172a;color:#e2e8f0;padding:2rem}
        h1{text-align:center;margin-bottom:2rem;color:#38bdf8}
        table{width:100%;max-width:700px;margin:0 auto;border-collapse:collapse;background:#1e293b;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.3)}
        th{background:#334155;padding:14px 16px;text-align:right;color:#94a3b8;font-size:.9rem}
        td{padding:14px 16px;border-bottom:1px solid #334155;font-size:.95rem}
        tr:last-child td{border-bottom:none}
        tr:hover td{background:#263348}
        .email{color:#38bdf8;font-family:monospace;font-size:.9rem}
        .pass{color:#a78bfa;font-family:monospace;font-size:.9rem;letter-spacing:.5px}
        .role{color:#64748b;font-size:.8rem}
        .note{text-align:center;margin-top:1.5rem;color:#f87171;font-size:.85rem}
    </style></head><body>
    <h1>🔑 بيانات الدخول</h1>
    <table><thead><tr><th>الاسم</th><th>الإيميل</th><th>الباسوورد</th><th>الدور</th></tr></thead><tbody>';

    foreach ($users as $u) {
        $roleName = $u->role->name ?? '—';
        $html .= "<tr>
            <td>{$u->name}</td>
            <td><span class=\"email\">{$u->email}</span></td>
            <td><span class=\"pass\">{$resetPassword}</span></td>
            <td><span class=\"role\">{$roleName}</span></td>
        </tr>";
    }

    $html .= '</tbody></table>
    <p class="note">⚠️ تم إعادة تعيين جميع كلمات المرور — احذف هذا الرابط بعد الاستخدام</p>
    </body></html>';

    return response($html);
});

Route::post('/public-reset-password', function (\Illuminate\Http\Request $request) {
    $request->validate(['email' => 'required|email', 'password' => 'required|string|min:6']);
    $user = \App\Models\User::where('email', $request->email)->firstOrFail();
    $user->password = \Illuminate\Support\Facades\Hash::make($request->password);
    $user->save();
    return response()->json(['message' => 'تم تغيير كلمة المرور بنجاح', 'user' => $user->only('id', 'name', 'email')]);
});

// Public Auth endpoint
Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:5,1');

// File serving for <img src>: no bearer token, but requires a signed, expiring URL
// generated by Attachment::getUrlAttribute(). See SEC-05.
Route::get('/attachments/{id}/file', [AttachmentController::class, 'getFile'])
    ->name('attachments.file')
    ->middleware('signed:relative');

// Pusher private channel auth (must be behind auth:sanctum)
Broadcast::routes(['middleware' => ['auth:sanctum']]);

// Protected API routes
Route::middleware('auth:sanctum')->group(function () {
    // User Management & Profile routes
    Route::get('/profile', [AuthController::class, 'profile']);
    Route::post('/logout', [AuthController::class, 'logout']);

    Route::get('/users', [UserController::class, 'index']);
    Route::post('/users', [UserController::class, 'store']);
    Route::put('/users/{id}', [UserController::class, 'update']);
    Route::delete('/users/{id}', [UserController::class, 'destroy']);
    Route::post('/users/{id}/impersonate', [UserController::class, 'impersonate']);

    Route::get('/roles', [RolePermissionController::class, 'indexRoles']);
    Route::get('/permissions', [RolePermissionController::class, 'indexPermissions']);

    // Projects CRUD & status management
    Route::get('/projects', [ProjectController::class, 'index']);
    Route::post('/projects', [ProjectController::class, 'store']);
    Route::get('/projects/{id}', [ProjectController::class, 'show']);
    Route::put('/projects/{id}', [ProjectController::class, 'update']);
    Route::delete('/projects/{id}', [ProjectController::class, 'destroy']);
    Route::post('/projects/{id}/restore', [ProjectController::class, 'restore']);
    Route::post('/projects/{id}/statuses', [ProjectController::class, 'addStatus']);
    Route::delete('/projects/{id}/statuses', [ProjectController::class, 'deleteStatus']);

    // Project Categories
    Route::get('/project-categories', [ProjectCategoryController::class, 'index']);
    Route::post('/project-categories', [ProjectCategoryController::class, 'store']);
    Route::put('/project-categories/{id}', [ProjectCategoryController::class, 'update']);
    Route::delete('/project-categories/{id}', [ProjectCategoryController::class, 'destroy']);

    // Tasks CRUD
    Route::get('/projects/{projectId}/tasks', [TaskController::class, 'index']);
    Route::post('/projects/{projectId}/tasks', [TaskController::class, 'store']);
    Route::put('/tasks/{id}', [TaskController::class, 'update']);
    Route::delete('/tasks/{id}', [TaskController::class, 'destroy']);

    // Task comments
    Route::get('/tasks/{taskId}/comments', [CommentController::class, 'index']);
    Route::post('/tasks/{taskId}/comments', [CommentController::class, 'store']);
    Route::delete('/comments/{id}', [CommentController::class, 'destroy']);

    // Custom fields management
    Route::post('/projects/{projectId}/custom-fields', [CustomFieldController::class, 'storeDefinition']);
    Route::delete('/projects/{projectId}/custom-fields/{fieldId}', [CustomFieldController::class, 'deactivateDefinition']);
    Route::post('/tasks/{taskId}/custom-fields', [CustomFieldController::class, 'setValue']);

    // Attachments uploads and deletes
    Route::post('/tasks/{taskId}/attachments', [AttachmentController::class, 'store']);

    Route::delete('/attachments/{id}', [AttachmentController::class, 'destroy']);

    // Folders routes
    Route::get('/projects/{projectId}/folders', [FolderController::class, 'index']);
    Route::post('/projects/{projectId}/folders', [FolderController::class, 'store']);
    Route::delete('/folders/{id}', [FolderController::class, 'destroy']);

    // Project files routes
    Route::get('/projects/{projectId}/project-files', [ProjectFileController::class, 'index']);
    Route::post('/projects/{projectId}/project-files', [ProjectFileController::class, 'store']);
    Route::get('/project-files/{id}/download', [ProjectFileController::class, 'download']);
    Route::delete('/project-files/{id}', [ProjectFileController::class, 'destroy']);

    // Notes routes
    Route::get('/projects/{projectId}/notes', [NoteController::class, 'index']);
    Route::post('/projects/{projectId}/notes', [NoteController::class, 'store']);
    Route::put('/notes/{id}', [NoteController::class, 'update']);
    Route::delete('/notes/{id}', [NoteController::class, 'destroy']);

    // Notifications management
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications', [NotificationController::class, 'store']);
    Route::post('/notifications/{id}/read', [NotificationController::class, 'markRead']);
    Route::post('/notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::post('/testing-notifications-helper', [NotificationController::class, 'createTestingHelper']);

    // Digest tooling exposes task titles across every project, so it stays
    // behind an administrative permission. See SEC-19.
    Route::middleware('permission:manage-users')->group(function () {
        Route::post('/digest/send', function () {
            Artisan::call('digest:send');
            return response()->json(['message' => 'تم إرسال الملخص بنجاح']);
        });

        Route::get('/digest/queue', function () {
            return response()->json(EmailDigestQueue::with('task')->get());
        });

        Route::get('/digest/emails', function () {
            return response()->json(BatchedEmail::orderBy('created_at', 'desc')->get());
        });
    });

    // Project templates CRUD routes
    Route::get('/project-templates', [ProjectTemplateController::class, 'index']);
    Route::post('/project-templates', [ProjectTemplateController::class, 'store']);
    Route::put('/project-templates/{id}', [ProjectTemplateController::class, 'update']);
    Route::delete('/project-templates/{id}', [ProjectTemplateController::class, 'destroy']);
    Route::post('/project-templates/{id}/set-default', [ProjectTemplateController::class, 'setDefault']);

    // Task templates CRUD routes
    Route::get('/task-templates', [TaskTemplateController::class, 'index']);
    Route::post('/task-templates', [TaskTemplateController::class, 'store']);
    Route::put('/task-templates/{id}', [TaskTemplateController::class, 'update']);
    Route::delete('/task-templates/{id}', [TaskTemplateController::class, 'destroy']);
    Route::post('/task-templates/{id}/set-default', [TaskTemplateController::class, 'setDefault']);

    // Daily Tasks routes
    Route::get('/daily-tasks', [DailyTaskController::class, 'index']);
    Route::post('/daily-tasks', [DailyTaskController::class, 'store']);
    Route::post('/daily-tasks/sync', [DailyTaskController::class, 'sync']);
    Route::put('/daily-tasks/{id}', [DailyTaskController::class, 'update']);
    Route::delete('/daily-tasks/{id}', [DailyTaskController::class, 'destroy']);

    // Daily journal notes (ملاحظات اليوميات)
    Route::get('/daily-notes', [DailyNoteController::class, 'index']);
    Route::post('/daily-notes', [DailyNoteController::class, 'store']);
    Route::delete('/daily-notes/{id}', [DailyNoteController::class, 'destroy']);

    // Habits routes (العادات)
    Route::get('/habits', [\App\Http\Controllers\HabitController::class, 'index']);
    Route::post('/habits', [\App\Http\Controllers\HabitController::class, 'store']);
    Route::post('/habits/sync', [\App\Http\Controllers\HabitController::class, 'sync']);
    Route::put('/habits/{id}', [\App\Http\Controllers\HabitController::class, 'update']);
    Route::delete('/habits/{id}', [\App\Http\Controllers\HabitController::class, 'destroy']);
});
